#ifndef MCAL_TMR_TMR_CFG_H_
#define MCAL_TMR_TMR_CFG_H_

#define TIMER0_STATE ENABLE
#define TIMER1_STATE ENABLE
#define TIMER2_STATE ENABLE

/*
 * Timer0 -> PWM Motor Left
 * Timer1 -> ICU
 * Timer2 -> PWM Motor Right
 */

#define TIMER0_MODE FAST_PWM
#define TIMER1_MODE ICU
#define TIMER2_MODE FAST_PWM


#define CLK_SELECT_PRESCALER_TIM0 CLK_8
#define CLK_SELECT_PRESCALER_TIM1 CLK_8
#define CLK_SELECT_PRESCALER_TIM2 CLK_8


#define DISCONNECTED   0
#define NON_INVERTING  1
#define INVERTING      2

#define PWM_OUTPUT_MODE NON_INVERTING

#define INTERRUPT_CONTROL DISABLE

#endif
