/*
 * TIMER_cfg.h
 *
 *  Created on: Aug 4, 2026
 *      Author: HP
 */

#ifndef MCAL_TIMER_TIMER_CFG_H_
#define MCAL_TIMER_TIMER_CFG_H_

// ENABLE AND DISABLE TIMERS
#define TIMER0_STATE				ENABLE
#define TIMER1_STATE				ENABLE
#define TIMER2_STATE                ENABLE

#define TIMER0_MODE					FAST_PWM
#define TIMER1_MODE					ICU
#define TIMER2_MODE                 FAST_PWM

// CONFIGURE PRESCALER
#define CLK_SELECT_PRESCALER_TIM0   CLK_8
#define CLK_SELECT_PRESCALER_TIM1   CLK_8
#define CLK_SELECT_PRESCALER_TIM2   CLK_8

// PWM OUTPUT MODES
#define DISCONNECTED	0
#define NON_INVERTING	1
#define INVERTING		2

#define PWM_OUTPUT_MODE	    NON_INVERTING

#define INTERRUPT_CONTROL	ENABLE

#endif /* MCAL_TIMER_TIMER_CFG_H_ */
