/*
 * ULTRASONIC_cfg.h
 *
 *  Created on: Aug 8, 2026
 *      Author: HP
 */

#ifndef HAL_ULTRASONIC_ULTRASONIC_CFG_H_
#define HAL_ULTRASONIC_ULTRASONIC_CFG_H_

#define ULTRASONIC_TRIG_PORT    DIO_PORTD
#define ULTRASONIC_TRIG_PIN     DIO_PIN4

#define ULTRASONIC_ECHO_PORT    DIO_PORTD
#define ULTRASONIC_ECHO_PIN     DIO_PIN6


#endif /* HAL_ULTRASONIC_ULTRASONIC_CFG_H_ */
